title: Pikidex DB

author:
  name: monjuik
  email: a.malinin@gmail.com

theme: minima

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-minifier
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]
